

###### PD Control Parameter Setting ############
distance_Tolerance: 0.1 # unit : meter
angle_Tolerance: 3      # unit : degree

p_distance_gain: 0.3
d_distance_gain: 0.1

p_angle_gain: 0.6
d_angle_gain: 0.1
#################################################

###### Frame Parameter Setting ##################
BaseFrame: base_footprint
CamFrame: camera
Camera_X_From_BaseFrame: 0
Camera_Y_From_BaseFrame: 0
Camera_Z_From_BaseFrame: 0.3
Camera_Yaw_From_BaseFrame: 90  # unit : degree 